### PR TITLE
Allow setting the router instance later on

### PR DESCRIPTION
**Pull request by marnusw**
Please see the changes I made to `README.md` for my motivation behind these proposed changes.

### CODE REVIEW

**Comment by LegitTalon** [comment]
Hello @marnusw Thank you for the pull request!

This module currently supports your desired behavior, albeit implicitly. I have added documentation to the README to be more explicit. It covers abstracting the isomorphic bits into a function that effectively accomplishes the behavior you've submitted.

Please let me know if the added docs do not accomplish what you had in mind. :smile:

**Comment by marnusw** [comment]
That is actually quite smart! :smile: I hadn't thought of wrapping the isomorphic parts in a function, it's a nice way to clean things up. Thanks for the feedback and for extending the docs!

**Comment by marnusw** [comment]
You might want to update the part for the client to be:
```
import Router from 'react-router';
const app = makeApp(Router.HistoryLocation);
```

**Comment by LegitTalon** [comment]
Updated. Thanks again!

**Comment by marnusw** [comment]
Hmm, wouldn't you still need a `plugin.getRouter()` method if the isomorphic bits are wrapped in a function  to get the instance and `.run()` the router later? One could create the router instance outside the scope of `makeApp()`, but if the isomorphic and client/server parts are in separate files then you'd have to export both the function and the router instance which seems undesirable. Getting it from the plugin might be better? (I can do a quick PR if you agree.)

**Comment by LegitTalon** [comment]
This might also be solvable with better documentation. In my application I am pulling the router off the context created by fluxible.

```javascript
const appContext = app.createContext()
appContext.getActionContext().router.run(() => {})
```

**Comment by marnusw** [comment]
Thinking about this some more I have a couple of points/concerns:

**Using getActionContext()**

1. It will work, but it seems to go against general approach in the examples as far as I can tell. As I understand it the whole idea behind `Fluxible.getPlugin('')` is to plug them in `isomorphic.js` and then configure them appropriately in `server.js` and `client.js` via this method.
2. (A more unopinionated reason:) Creation of the context is lazy. The component context is always required, and pulling data from stores on the server makes the store context required. But in many cases the action context is not retrieved (at least in my app) which technically provides the smallest of performance improvements. If the action context is retrieved in `server.js` it means it will be instantiated on every request.

**Another workaround** (Though I vote for my next point.)

Rather than passing the `routes` as the Fluxible component, which is not necessary if the router is created immediately thereafter, you could do:

```javascript
const router = Router.create({
  routes: require('./mainRoutes.jsx'),
  location: url
});
const app = new Fluxible({
  component: router
});
app.plug(reactRouter(router))
```

And to run the router later you would

```javascript
const app = makeApp(req.url)
app.getComponent().run(...);
```

Although this is decidedly not the way Fluxible was designed to work. (I'd still prefer using `plugin.getRouter()`)

**Additional Router config options**

[`Router.create()`](http://rackt.github.io/react-router/#Router.create) has various options other than `routes` and `location` which are client/server specific: `scrollBehavior` for clients, `onAbort` and `onError` for the server. It seems to make sense that these would be specified in the client/server specific scripts. Again they can be passed to the `makeApp()` function though. 

But... In my server code after wrapping the isomorphinc parts in the function I had to call it to create the app within a function where the `url` is present. Then I had to start passing the app variable around as a parameter to other functions, whereas I could just import the exported app object at the top of my server script previously which I now, again, tend to prefer. (Sure I can still define the `app` variable at the top and assign it in the function, but that always seems brittle to me.) 

Since this plugin will be the standard used by many developers with varying needs, don't you think a simple `getRouter()/setRouter()` on the plugin might make sense after all?

**Comment by LegitTalon** [comment]
I'd like to see if there are any ways to solve these issues without adding the plugin methods and instead preferring documentation examples. My hesitation is that the router probably _should_ be fairly difficult to access from anywhere other than the actionContext. The exception being when one needs to `.run` it. I hope that seems valid.

**Comment by marnusw** [comment]
OK, I agree with the principle of limiting access to the router. 

An important thing I want to note is that you can still only do `app.getPlugin('ReactRouterPlugin').getRouter()` when you have access to the `app` variable, which will only be in the startup scripts (`iso.js client.js server.js`) and not in the application proper. I therefore don't necessarily feel we're breaking encapsulation there, on the contrary, I think we'll be exposing configurability in the exact way Fluxible was designed for. 

That said, let me see if I can update the code to allow running the router later and I'll reopen this PR. Then we can resume the discussion from there...

**Comment by LegitTalon** [comment]
Sounds good. I think I understand your point now.

**Comment by marnusw** [comment]
I've added the `.run()` method in #2. I've actually decided to go your proposed route and wrap the app creation in a function, so this is all I need for now. Adding `setRouter` or `getRouter` can be postponed until someone really has the need for it.

**Pull request closed without merging**
