### PR TITLE
react-router v1.0.0-rc1

### PR DESCRIPTION
**Pull request by marnusw**
Hey @LegitTalon 

I'm finally migrating to `react-router v1.0.0` which is now at `rc1` and the changes are indeed such that this plugin in its current form doesn't seem sufficient (#3).

For one, the `run` method is gone! Client side routing is now realized by rendering a `<Router>` component with the routes [[docs](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#rendering)], and server side routing is done with the lower level API [[docs](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md)].

Initiating transitions is now handled via a [`history`](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md) component, which is what we'll need to keep track of on the action context to realize navigation in actions.

The `react-router` team has a solution for what we're trying to do [here](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md), which could make this plugin obsolete. However, it doesn't seem to work with isomorphic code (rackt/react-router#2076), which is why I made this initial stab at a revised plugin.

What do you think?

CC @eriknyk @jeffreywescott

### CODE REVIEW

**Comment by LegitTalon** [comment]
This seems like it'll work. Have you tested it? I don't currently use fluxible.

We should consider how to version this library along with React router. IT would have been nice to mimic versions but I already messed that up.

**Comment by marnusw** [comment]
Yes, I'm using it and so far so good. I'll give it a bit more time to make sure it meets all needs, and to see if I get feedback from the router team.

I guess we can just go with v2.0.0 for the plugin as soon as they realease v1.0.0. For now perhaps our own 2.0.0-rc1 one it's ready.

**Comment by LegitTalon** [comment]
Yeah that seems reasonable.

**Comment by LegitTalon** [comment]
The docs will also need to reflect the new usage.

**Comment by marnusw** [comment]
Jip, I'll definitely update the docs before we release anything.

**Comment by marnusw** [comment]
@LegitTalon I have updated the docs and finalized the implementation which is working perfectly for me at the moment. If an additional use case crops up that's not catered for I think we can release a patch. For now I'd like to get this version out there.

Would you please let me know if you're happy with proceeding? Then I'll merge and tag it, and just ask you to publish to npm please.

**Comment by LegitTalon** [comment]
Excellent. Let's squash this, merge and tag. I'll add you to the npm maintainers list so you can do releases.

**Comment by marnusw** [comment]
All done, thanks for your input @LegitTalon.

**Comment by LegitTalon** [comment]
Crushin' it! Thank you @marnusw

**Pull request merged**
